### PR TITLE
updated docker files for azure-cli 0.9.7 and 0.9.8 versions

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@amarzavery LGTM. Want to create a Docker Hub account so that I can add you as maintainer over there to add update tags (unfortunately they're not automatic and they require manual intervention).

**Comment by ahmetalpbalkan** [comment]
anyway no worries I added them manually on docker hub this time.

**Comment by ahmetalpbalkan** [comment]
build consistently fails for some stupid reason. docker hub is buggy.
https://hub.docker.com/r/microsoft/azure-cli/builds/bzyzp8bz4gjpcakda4btijd/
https://hub.docker.com/r/microsoft/azure-cli/builds/brdnbt6e2aeahuywykdn8vg/

I think until this is fixed (and we trigger a new build) the new tags won't show up unfortunately.

**Comment by amarzavery** [comment]
Hi Ahmet,

Sorry for not being able to respond. I was out of network coverage hence did not receive the email. Please add me to the repo. I will add this to be done as a part of xplat cli release activities.

Thanks,
Amar Zavery

On Aug 21, 2015, at 7:22 PM, "Ahmet Alp Balkan" <notifications@github.com<mailto:notifications@github.com>> wrote:


anyway no worries I added them manually on docker hub this time.

-

**Comment by ahmetalpbalkan** [comment]
@amarzavery what's your docker hub username?

**Comment by amarzavery** [comment]
My username is amarzavery.

Thanks,
Amar Zavery

On Aug 21, 2015, at 8:20 PM, "Ahmet Alp Balkan" <notifications@github.com<mailto:notifications@github.com>> wrote:


@amarzavery<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2famarzavery&data=01%7c01%7camzavery%40microsoft.com%7c3a6b69e066294dd3df5908d2aaa0a6e0%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=UPQ9kWjVbQeZSA3i1hdX1LYnh8gWIwkrHpuJubSBAks%3d> what's your docker hub username?

-

**Comment by ahmetalpbalkan** [comment]
@amarzavery added you as an admin to the image. Please check the Docker Hub interface an get familiar with it for the next time. :) 

Images are now ready at https://hub.docker.com/r/microsoft/azure-cli/tags/

**Pull request merged**
