### PR TITLE
update cli to 0.9.9

### PR DESCRIPTION
**Pull request by devigned**
- upgrade to 0.9.9
- add .gitignore for .DS_Store files

### CODE REVIEW

**Comment by devigned** [comment]
@ahmetalpbalkan are you able to add @amarzavery to the contributors list.

**Comment by ahmetalpbalkan** [comment]
@devigned http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit you can do it yourself and push -f if you like? We don't have a contributors list on the repo? (wait, do you mean Docker Hub image admins list?)

**Comment by devigned** [comment]
Thank you for the git pro tip ;). I was thinking it would be useful to add Amar as someone that can accept pull requests in GitHub for this project.

**Comment by ahmetalpbalkan** [comment]
@devigned aah ok. I think we just need to add your team to the repo as collaborator. I couldn't find that on azuregithub site, will follow up internally.

**Comment by ahmetalpbalkan** [comment]
LGTM please feel free to merge and release on Docker Hub.

**Pull request merged**
