### PR TITLE
update azure to 0.9.6, move to debian, add autocomplete and tools

### PR DESCRIPTION
**Pull request by devigned**
## Things done
- update azure to 0.9.6
- move to debian
- add autocomplete
- tools

relevant issues: #13, #12, #6

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
I think you havent deleted the 0.9.5/readme.md. Also what do you think about jq pkg mentioned in #6, it comes really handy for json validation in ARM template authoring use cases.

**Comment by devigned** [comment]
Good call on jq. I thought I had that in there. Updated.

**Comment by ahmetalpbalkan** [comment]
Lgtm.

**Comment by ahmetalpbalkan** [comment]
@devigned forgot to ask, why did you choose to install python as well?

also I realized `vi`/`vim`/`nano` are missing from this release, we should probably address that as they are essential as well.

**Comment by devigned** [comment]
@ahmetalpbalkan I like having python available for scripts. I find it more suitable than node for most simple tasks.

I created #15 to remind us to add vi / vim / nano.

**Pull request merged**
