### PR TITLE
update to azure-cli 0.9.4

### PR DESCRIPTION
**Pull request by devigned**
Create a new directory and dockerfile for the latest cli version.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
README needs to be mv'ed here and symlink needs to be updated.

**Comment by devigned** [comment]
@ahmetalpbalkan mv'd the readme and updated symlink

**Comment by devigned** [comment]
one sec

**Comment by devigned** [comment]
ok, added the readme back :boom:

**Comment by ahmetalpbalkan** [comment]
Lgtm. Feel free to merge and update Docker Hub.

**Comment by ahmetalpbalkan** [comment]
there's a problem with Docker Hub... I'm gonna follow up with support@docker.com coz I've seen this happening on other images (outside MSFT account as well).

**Comment by devigned** [comment]
Thx for following up on that error.

**Comment by ahmetalpbalkan** [comment]
Fixed now, it turns out there was an issue with Docker Hub.

**Pull request merged**
